### ISSUE TITLE
Cannot read properties of undefined (reading '0') : var sel = $(selected.args[0]);

### ISSUE THREAD

**Issue by krunal2212** [UltimateModuleCreator/Umc_Base#45]
umc.js:253 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at HTMLDivElement.<anonymous> (umc.js:253:42)
    at HTMLDivElement.dispatch (jquery.js:5430:49)
    at elemData.handle (jquery.js:5234:47)
    at Object.trigger (jquery.js:8719:28)
    at jQuery.fn.init.triggerHandler (jquery.js:8803:37)
    at $.jstree.core.trigger (jquery.jstree.js:960:26)
    at $.jstree.core.select_node (jquery.jstree.js:3288:22)
    at $.jstree.core.activate_node (jquery.jstree.js:3155:26)
    at $.jstree.core.<anonymous> (jquery.jstree.js:777:26)
    at HTMLDivElement.dispatch (jquery.js:5430:49)

**Comment by dfelton** [comment]
@krunal2212 this is an unmaintained project at this point (since 2018).
